print("Finish the lyrics to this song from the sound of music")

Line1 = input("Raindrops on:")
Line2 = input("And whiskers on:")
Line3 = input("Bright copper:")
Line4 = input("And warm woolen:")
Line5 = input("Brown paper packages:")
Line6 = input("These are a few of my:")
print(Line1,"roses")
print(Line2,"kittens")
print(Line3,"kettles")
print(Line4,"mittens")
print(Line5,"tied up with strings")
print(Line6,"favorite things")
print(" Thanks for playing")
